version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - odoopg
      - odoopd
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/logs:/var/log/nginx
    environment:
      - NGINX_PG_HOST=${PG_ODOO_HOST}
      - NGINX_PD_HOST=${PD_ODOO_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "16"

  odoopg:
    image: odoo:16
    platform: linux/amd64
    container_name: "odoopg"
    restart: always
    volumes:
      - ./odoopg/files:/var/lib/odoo
      - ./odoopg/config:/etc/odoo
      - ./odoopg/addons:/mnt/extra-addons
    environment:
      - HOST=${PG_HOST}
      - PORT=${PG_PORT}
      - USER=${PG_USER}
      - PASSWORD=${PG_PASS}
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "16"

  odoopd:
    image: odoo:16
    platform: linux/amd64
    container_name: "odoopd"
    restart: always
    volumes:
      - ./odoopd/files:/var/lib/odoo
      - ./odoopd/config:/etc/odoo
      - ./odoopd/addons:/mnt/extra-addons
    environment:
      - HOST=${PD_HOST}
      - PORT=${PD_PORT}
      - USER=${PD_USER}
      - PASSWORD=${PD_PASS}
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "16"
